resolver: lts-9.6
packages:
- '.'
- location:
    git: git@github.com:mvdan/hint.git
    commit: f10e357d8249bc4b8a71e2c211bebc202549c765
  extra-dep: true
extra-deps:
- tidal-midi-0.9.4
- PortMidi-0.1.6.0
flags: {}
extra-package-dbs: []
